#OPT_DEFS += -DRGB_MATRIX_STARTUP_MODE=RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
TAP_DANCE_ENABLE=yes
OPT_DEFS += -DRGB_MATRIX_FRAMEBUFFER_EFFECTS -DVMALLOC_DISABLE_RGB_ON_STARTUP
RAW_ENABLE=yes
CONSOLE_ENABLE=yes
